server:
  port: 9090
  servlet:
    context-path: "/api/v1"
    error:
      include-stacktrace: never
      include-message: never

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:bookDB
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernates:
        format_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: NON_NULL